### ISSUE TITLE
"PyCharm" requests for contacts access, photos access, notifications access, and folders access

### ISSUE THREAD

**Issue by niibruce** [carbonblack/intellij-rpmspec#10]
See here: https://ibb.co/3BjVx96

**Comment by tlusk** [comment]
This looks to be an upstream issue with IntelliJ/PyCharm and is not an issue with this plugin.

See: https://intellij-support.jetbrains.com/hc/en-us/articles/360001849319-IDE-requests-access-to-calendar-contacts-photos-etc-on-macOS-Mojave
