### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by paul-dingemans** [carbonblack/intellij-rpmspec#19]
### Describe the bug

You might want to fix the typo in `ktlint_experimental` to enable the experimental rules of ktlint:
```
    kotlin {
        ktlint(ktlintVersion)
            .editorConfigOverride(mapOf("ktlint_experimentasl" to "enabled"))
    }
```

Also, you can remove property below as it is invalid (the correct property is already on the line below it):
```
ktlint_experimental_property-naming = disabled
```

### Reproduction steps

N/A

### Expected behavior

N/A

**Comment by tlusk** [comment]
Resolved in #20, thanks for the heads up!
