### ISSUE TITLE
Icon not rendered correctly

### ISSUE THREAD

**Issue by thaJeztah** [carbonblack/intellij-rpmspec#3]
Both in Goland 2019.3.1, and IntelliJ IDEA 2020.1 (Community Edition), the icon does not render correctly; the background of the icon is scaled, but filled "red" instead of transparent. (Possibly the Intellij platform doesn't handle the gradients correctly?)

I'm running on macOS Mojave (10.4.6) on a retina screen. Here's some screenshots:

<img width="176" alt="Screenshot 2020-04-10 at 09 20 37" src="https://user-images.githubusercontent.com/1804568/78972457-175dc000-7b0e-11ea-839f-adcd5f5c8c35.png">
<img width="204" alt="Screenshot 2020-04-10 at 09 20 43" src="https://user-images.githubusercontent.com/1804568/78972458-17f65680-7b0e-11ea-98a0-cdd93e825aaa.png">
<img width="263" alt="Screenshot 2020-04-10 at 09 31 31" src="https://user-images.githubusercontent.com/1804568/78972459-17f65680-7b0e-11ea-9a7a-7d76f9179f2a.png">

The problem reproduced both in "dark" (darkula) and light mode

And info of the versions I'm running;

<img width="640" alt="Screenshot 2020-04-10 at 09 22 26" src="https://user-images.githubusercontent.com/1804568/78972507-36f4e880-7b0e-11ea-9854-cb1543ffad56.png">
<img width="640" alt="Screenshot 2020-04-10 at 09 35 07" src="https://user-images.githubusercontent.com/1804568/78972697-a23eba80-7b0e-11ea-9b81-f25c20a1cd80.png">

I tried looking at the docs but nothing really stood out (other than there's no `_dark` variants of the icon); https://www.jetbrains.org/intellij/sdk/docs/reference_guide/work_with_icons_and_images.html

> The naming notation used for PNG icons (see below) is still relevant. However, the @2x version of an SVG icon should still provide the same base size. The icon graphics of such an icon can be expressed in more details via double precision. If the icon graphics are simple enough so that it renders perfectly in every scale, then the @2x version can be omitted.

**Comment by thaJeztah** [comment]
@tlusk ptal 🤗

**Comment by tlusk** [comment]
🤔 That is strange, I'm not seeing that in IntelliJ 2020.1 ultimate edition under OpenSUSE and CentOS.

![icons](https://user-images.githubusercontent.com/458460/79008944-6e728d80-7b2c-11ea-998b-6732f7e8f613.png)

I'll see what I can do to try to reproduce it but if I can't I'm not sure what I'd do to fix it.  I'll take a look soon.

**Comment by tlusk** [comment]
Very quick update, I was able to reproduce it already by changing the OpenSUSE scaling to 200% 😄 

![scale](https://user-images.githubusercontent.com/458460/79009482-8a2a6380-7b2d-11ea-8e93-f1fd5b515d39.png)

I'll see what I can do!

**Comment by tlusk** [comment]
@thaJeztah found the issue, it's resolved in 1.1.1 which has been uploaded to the plugin repo and will be approved within the next 48 hours.

**Comment by thaJeztah** [comment]
Oh, wow, thanks for taking a look, and happy to see you were able to find the problem! I'll look out for the 1.1.1 patch release 🎉 🥳

**Comment by thaJeztah** [comment]
The updates arrived, and I can confirm the issue is fixed. Thanks again!
